---
apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  ports:
  - port: 3306
  selector:
    app: mysql
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - image: mysql:5.6
        name: mysql
        envFrom:
        - secretRef:
            name: database-secret
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: hostpath-dir
          mountPath: /var/lib/mysql
      volumes:
      - name: hostpath-dir
        hostPath:
          path: /mnt/minidata
          type: DirectoryOrCreate
