apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: managed-fusion-ns
namePrefix: mock-
images:
- name: mockserver
  newName: quay.io/jarrpa/mock-cdr-server
  newTag: latest
resources:
- mock-api-server.yaml
- database.yaml
secretGenerator:
- behavior: create
  literals:
  - MYSQL_ROOT_PASSWORD=password
  name: database-secret
