---
apiVersion: v1
kind: Service
metadata:
  name: cdr-service
spec:
  ports:
  - port: 10000
  selector:
    app: cdr-server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cdr-server
spec:
  selector:
    matchLabels:
      app: cdr-server
  replicas: 1
  template:
    metadata:
      labels:
        app: cdr-server
    spec:
      containers:
      - command:
        - /mockserver
        image: mockserver:latest
        imagePullPolicy: Always
        name: mockserver
        ports:
        - containerPort: 10000
          name: cdr-server
