---
name: image-builder

on:
  push:
    branches: ['*']
  pull_request:
    branches: ['*']

jobs:
  container-build:
    name: metering-reporter-build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        go: ["1.18", "1.19"]
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}

      - uses: actions/checkout@v2

      - name: Build operator container image
        run: make build
